backend:
  name: github
  repo: dahaekim88/blog-portfolio-website

media_folder: static/assets
public_folder: assets

collections:
  - name: Blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: tags, label: Tags, widget: list, default: ["javascript"] }
      - {
          name: category,
          label: Category,
          widget: select,
          options: ["blog", "projects"],
        }
      - { name: description, label: Description, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }
  - name: Projects
    label: Projects
    folder: src/pages/projects
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description, widget: text }
      - { name: image, label: image, widget: image }
      - { name: gif, label: gif, widget: image }
      - { name: demo, label: demo, widget: text }
      - { name: source, label: source, widget: text }
      - { name: body, label: Body, widget: markdown }
