backend:
  name: github
  repo: dahaekim88/blog-portfolio-website

media_folder: static/assets
public_folder: assets

collections:
  - name: Blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }
